### PR TITLE
Update pulsar dependency to 2.10.3

### PR DESCRIPTION
**Pull request by aymkhalil**
2.8 has performance reported issue, recommended to update to 2.10.x. Please note that the connector pulsar client will be vended by the environment, but this upgrade benefits the agent. It also unified the client version between the Agent and CLI tool. 

Notes:
* The maxPendingMessagesAcrossPartitions has been deprecated as of pulsar 2.10 (see [PIP-120](https://github.com/apache/pulsar/pull/13344))
* I couldn't upgrade to 2.11 because it required java 17. CDC need to compile with java 11 too. Sample build error:
```
bad class file: /home/runner/.gradle/caches/modules-2/files-2.1/org.apache.pulsar/pulsar-functions-api/2.11.0/6abd8cd6cf9b9a6ef15a7e53882577a897dcaf8a/pulsar-functions-api-2.11.0.jar(/org/apache/pulsar/functions/api/KVRecord.class)
    class file has wrong version 61.0, should be 55.0
```

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
Switching to 2.10.x requires more work.

The default settings changed a lot, by default now there is a limit on the memory used by the producer and not on the number of pending messages.

I suggest to apply a default configuration similar to 2.8.3

Please take a look to the changes we did in CNDB in order to achieve better results.

The gist of it is to disable the memory limit and configure the max pending messages

**Comment by aymkhalil** [comment]
@eolivelli 
* The `maxPendingMessage` is [configured](https://github.com/datastax/cdc-apache-cassandra/blob/85de1640f70b3f56f5b9ec15073f3be63cbcc76e/agent/src/main/java/com/datastax/oss/cdc/agent/AbstractPulsarMutationSender.java#L200) on the producer and has [default](https://github.com/datastax/cdc-apache-cassandra/blob/85de1640f70b3f56f5b9ec15073f3be63cbcc76e/agent/src/main/java/com/datastax/oss/cdc/agent/AgentConfig.java#L294) value already
* CNDB uses client 2.10.0 that doesn't have the fix for the memory limit. This patch uses 2.10.3 which has the [fix](https://github.com/apache/pulsar/commit/7c73269cda7855045428a3d53df09632cfbbde94)
* I added the configuration for `memoryLimit` that is disabled by default anyway. 
* `maxPendingMessagesAcrossPartitions` is deprecated and I think it is better to drop it as I don't expect future support for it

PTAL.

**Comment by aymkhalil** [comment]
For some reason, 2 tests are failing with:
```
java.lang.AssertionError: Wrong value for regular field double expected:<1.0> but was:<1>
```

The tests was using the shaded jackson from pulsar client, I updated it to use the jackson dependency directly in the tests: https://github.com/datastax/cdc-apache-cassandra/blob/87586fb7ac0cee7d6c4e21f4ec0f02608675ca01/connector/build.gradle#L47 to see if it helps

**Review by eolivelli — APPROVED** [review]
Lgtm

**Pull request merged**
