### PR TITLE
Drop Luna Streaming 2.7.x support

### PR DESCRIPTION
**Pull request by nicoloboschi**
* Removed all the matrix projects combination (-luna, -pulsar). now there is only
  * agent
  * commons
  * connector
  * ...
and they all use LunaStreaming/Pulsar 2.8.x

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Lgtm

As far as it works with Luna Streaming 2.8 and Pulsar 2.8

**Comment by nicoloboschi** [comment]
@eolivelli I pushed a fix for the docker-compose part.

Now if you follow the doc, you are able to create a local docker cluster with 
- C* and the agent (Apache Pulsar client)
- Luna Streaming 2.8.0.x 
- ElasticSearch
- Grafana

And you can see data flowing to ElasticSearch without issues.

**Comment by eolivelli** [comment]
@mendonk we should follow up and remove all the references to the "luna" artifacts in docs.

@nicoloboschi can you please guide @mendonk  ?

**Comment by nicoloboschi** [comment]
sure. https://github.com/datastax/cdc-apache-cassandra/issues/56

**Pull request merged**
